### ISSUE TITLE
Flux networks crash - Repeatable

### ISSUE THREAD

**Issue by AndersWithTheCat** [FTBTeam/FTB-Presents-Stoneblock-2#187]
* **Modpack Version**: 1.0.1-1.2.0 (tested on all)
* **Issue**: Placing a flux networks point or plug on a AE2 Energy cell with crash the server due to interactions with AE2 power for some reason

* **Link to Log or Crash File Paste**: 
java.lang.NullPointerException: Exception in server tick loop
    at appeng.tile.networking.TileEnergyCell.injectAEPower(TileEnergyCell.java:160)
    at sonar.core.handlers.energy.tiles.TileHandlerAppliedEnergistics.addEnergy(TileHandlerAppliedEnergistics.java:47)
    at sonar.flux.connection.transfer.ConnectionTransfer.removeFromNetwork(ConnectionTransfer.java:57)
    at sonar.flux.api.energy.internal.IEnergyTransfer.lambda$removeFromNetworkWithConvert$1(IEnergyTransfer.java:18)
    at sonar.core.handlers.energy.EnergyTransferHandler.convertedAction(EnergyTransferHandler.java:193)
    at sonar.flux.api.energy.internal.IEnergyTransfer.removeFromNetworkWithConvert(IEnergyTransfer.java:18)
    at sonar.flux.connection.transfer.handlers.FluxTransferHandler.removeFromNetwork(FluxTransferHandler.java:48)
    at sonar.flux.connection.FluxNetworkServer.onEndServerTick(FluxNetworkServer.java:118)
    at sonar.flux.network.FluxCommon.onServerTick(FluxCommon.java:114)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1123_FluxCommon_onServerTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)
* **Is it Repeatable?**:  Yes

* **Mod/s Affected**:  Ae2, Flux networks, 
* **Known Fix**: Disable AE conversion in Flux networks config or black list Ae2 cells in config(most likly the best)

Edit. tryed to disable the AE interaction and still got a server in a crash loop so tbh i think it needs to be fixed within the mod. rip

**Comment by AndersWithTheCat** [comment]
Fixed by editing FLux networks config 

From 
blacklists {
    # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
    S:"Block Connection Blacklist" <
        actuallyadditions:block_phantom_energyface
     >

To 
blacklists {
    # a blacklist for blocks which flux connections shouldn't connect to, use format 'modid:name'
    S:"Block Connection Blacklist" <
        actuallyadditions:block_phantom_energyface
        appliedenergistics2:dense_energy_cell
        appliedenergistics2:energy_cell
     >

i don't know if theres other AE blocks that might do the same but i founda fix after a few restarts :)
