### ISSUE TITLE
Ignoring Visibility Rule

### ISSUE THREAD

**Issue by crunchynut609** [FTBTeam/FTB-Presents-Stoneblock-2#362]
**Modpack Version:** 
1.6.0

**Issue:** 
so I've just installed this modpack today 25/02/19 and all was going well until I pressed play in the launcher where it downloaded everything necessary to play but crashed and said "game ended in bad state" "Ignoring visibility rule and showing launcher due to a game crash"

**Link to Log or Crash File Paste:** 
https://paste.feed-the-beast.com/view/1c369ce8 

**Is it Repeatable?:** 
yes repeatable 

please let me know if there is anything that can be done about this issue as I would really love to play the modpack.

**Comment by Sunekaer** [comment]
crash log?

**Comment by crunchynut609** [comment]
I think this is it

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Sunekaer** [comment]
No need the report there is in the folder called crash-reports

**Comment by crunchynut609** [comment]
[09:40:59] [Client thread/INFO]: Setting user: Crunchy_Nut_609
[09:41:00] [Client thread/INFO]: LWJGL Version: 2.9.2
[09:41:00] [Client thread/INFO]: Reloading ResourceManager: Default
[09:41:01] [Sound Library Loader/INFO]: Starting up SoundSystem...
[09:41:01] [Thread-2/INFO]: Initializing LWJGL OpenAL
[09:41:01] [Thread-2/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[09:41:01] [Thread-2/INFO]: OpenAL initialized.
[09:41:01] [Sound Library Loader/INFO]: Sound engine started
[09:41:03] [Client thread/INFO]: Created: 1024x512 textures-atlas
[09:41:43] [Server thread/INFO]: Starting integrated minecraft server version 1.12.2
[09:41:43] [Server thread/INFO]: Generating keypair
[09:41:44] [Server thread/INFO]: Loaded 488 advancements
[09:41:44] [Server thread/INFO]: Preparing start region for level 0
[09:41:45] [Server thread/INFO]: Preparing spawn area: 9%
[09:41:46] [Server thread/INFO]: Preparing spawn area: 21%
[09:41:47] [Server thread/INFO]: Preparing spawn area: 34%
[09:41:48] [Server thread/INFO]: Preparing spawn area: 49%
[09:41:49] [Server thread/INFO]: Preparing spawn area: 64%
[09:41:50] [Server thread/INFO]: Preparing spawn area: 80%
[09:41:51] [Server thread/INFO]: Preparing spawn area: 97%
[09:41:51] [Server thread/INFO]: Changing view distance to 12, from 10
[09:41:53] [Server thread/INFO]: Crunchy_Nut_609[local:E:3a5f9163] logged in with entity id 1480 at (185.5, 61.0, 246.5)
[09:41:53] [Server thread/INFO]: Crunchy_Nut_609 joined the game
[09:41:56] [Client thread/INFO]: Loaded 7 advancements
[09:41:56] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2509ms behind, skipping 50 tick(s)
[09:42:10] [Client thread/INFO]: Stopping!
[09:42:10] [Client thread/INFO]: SoundSystem shutting down...
[09:42:10] [Server thread/INFO]: Stopping server
[09:42:10] [Server thread/INFO]: Saving players
[09:42:10] [Server thread/INFO]: Crunchy_Nut_609 lost connection: Disconnected
[09:42:10] [Server thread/INFO]: Crunchy_Nut_609 left the game
[09:42:10] [Server thread/INFO]: Stopping singleplayer server as player logged out
[09:42:10] [Server thread/INFO]: Saving worlds
[09:42:10] [Server thread/INFO]: Saving chunks for level 'New World'/overworld
[09:42:10] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com

**Comment by crunchynut609** [comment]
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 31/01/19 2:46 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at cgc.<init>(SourceFile:23)
	at cft.am(SourceFile:438)
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at cgc.<init>(SourceFile:23)
	at cft.am(SourceFile:438)

-- Initialization --
Details:
Stacktrace:
	at cft.a(SourceFile:380)
	at net.minecraft.client.main.Main.main(SourceFile:144)

-- System Details --
Details:
	Minecraft Version: 1.13.2
	Operating System: Mac OS X (x86_64) version 10.14.1
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 97372608 bytes (92 MB) / 201326592 bytes (192 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.13.2
	LWJGL: 3.1.6 build 14
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Probably not. Jar signature remains and client brand is untouched.
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: ~~ERROR~~ NullPointerException: null
	Profiler Position: N/A (disabled)
	CPU: <unknown>

**Comment by crunchynut609** [comment]
I have no idea how to find the stone block crash reports. that last one is from the 'Minecraft' folder in application support.

**Comment by crunchynut609** [comment]
I've got no idea where to go to find the crash reports for stone block

**Comment by crunchynut609** [comment]
Im on Mac by the way if that helps. I have 8gb of memory and 4 allocated to running stone block 2. I have the latest version of java.

**Comment by Sunekaer** [comment]
Twitch logs can be found in the installation directory for the Twitch App.  Or click the "..." button on Stoneblock 2 and hit "Open Folder"

**Comment by Sunekaer** [comment]
and use http://paste.feed-the-beast.com/ to paste the text of your log/crash file

**Comment by crunchynut609** [comment]
this is all I could find in the folder for ftb presents stone block 2

https://paste.feed-the-beast.com/view/46056101

**Comment by Sunekaer** [comment]
Thats not the crash log. thats the last part of the latests log.......
This says nothing but that you have something in your world lagging the world out, how much have you done in this world?

**Comment by crunchynut609** [comment]
I haven't done anything, I haven't even seen the world

**Comment by Sunekaer** [comment]
Well seems like your pc cant handle the pack, i dont know
