### ISSUE TITLE
I am unable to launch the modpack from the twitch launcher

### ISSUE THREAD

**Issue by luv2die** [FTBTeam/FTB-Presents-Stoneblock-2#365]
version 1.6.0

Every time I try to launch the modpack from the twitch launcher it crashes and give me an error

this is what it shows in Game Output:

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[08:59:47] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[08:59:47] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraftforge.fml.common.launcher.FMLTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

It repeats every time I try to launch

**Comment by Sunekaer** [comment]
crash log?..

**Comment by luv2die** [comment]
I guess so but it has my username and then has in parentheses (Game Output)

**Comment by Sunekaer** [comment]
I need the crash log

**Comment by mendel3** [comment]
@luv2die just replace your username with REDACTED

**Comment by mendel3** [comment]
Also @Sunekaer it looks like the issue is caused by Java 9 or above. Not sure though..
