### ISSUE TITLE
Unable to use server

### ISSUE THREAD

**Issue by staj-d** [FTBTeam/FTB-Presents-Stoneblock-2#412]
* **Modpack Version**: 1.8.0

* **Issue**: Server log spam, random player disconnect, unplayable

* **Link to Log or Crash File Paste**: It's literally 1.5 GB... 13515262 lines...... Chrome crashes when I try to copy-paste it...
Spam of: `[17:21:16] [Netty Server IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.writev0(Native Method) ~[?:1.8.0_201]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:55) ~[?:1.8.0_201]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_201]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[?:1.8.0_201]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:432) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:856) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:368) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:618) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476) [minecraft_server.1.12.2.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) [minecraft_server.1.12.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [minecraft_server.1.12.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]`
* **Is it Repeatable?**: Yes

1. make server
2. open stoneblock 2 (on same computer)
3. join
4. wait
5. profit

* **Known Fix**: Nope, I've tried nuking the server (just keeping the world) and it still broke. Also, when I tried to use the world in singleplayer my items disappeared, so... Not an option.

**Comment by Sunekaer** [comment]
Hey

I havent been able to recreate your problem with my test server and local server, check your firewall and antivirus would be my guess
