### ISSUE TITLE
ServerStart.sh fails

### ISSUE THREAD

**Issue by jackthemoo** [FTBTeam/FTB-Presents-Stoneblock-2#457]
Downloaded the latest server release file 
FTBPresentsStoneblock2Server_1.9.0.zip
steps i've taken
1) Extract files,
2) made FTBInstall.sh, settings.sh, and ServerStart.sh all executable with chmod +x
3) executed all .sh files in that order using ./
When running ServerStart.sh this is the output

Missing eula.txt. Startup will fail and eula.txt will be created
Make sure to read eula.txt before playing!
To continue press <enter>
]
Starting server
Unrecognized VM option 'UseParNewGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I decided to try a basic server start command and then got this
java -Xmx2048M -Xms1024M -jar FTBserver-1.12.2-14.23.5.2808-universal.jar

A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 6 more

not sure the issue i have used the same process with other FTB packs

**Comment by Sunekaer** [comment]
"Make sure to read eula.txt before playing!" open the eula.txt and read that

**Comment by acidicchip** [comment]
@Sunekaer You did not answer the question. If you read it thoroughly...

It says...

> Missing eula.txt. Startup will fail and eula.txt will be created
> Make sure to read eula.txt before playing!
> To continue press 

Which means that after continuing the server would complain about the eula.txt, which is not even being generated because it's crashing.

I manually created the eula.txt, etc. and ran ./ServerStart.sh and am STILL getting the same error the OP is.

```
Starting server
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and ja
va.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```
