### ISSUE TITLE
Stoneblock 2 xaeros minimap crash

### ISSUE THREAD

**Issue by RampagedAlpaca** [FTBTeam/FTB-Presents-Stoneblock-2#616]
Whenever I try to join a server or start a singleplayer it says "Minecraft ran into a problem and crashed. The following mod(s) have been identified as potential causes. Xaero's Minimap.

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2019-08-18 17:09:58 CDT
Description: Unexpected error

java.lang.NoClassDefFoundError: xaero/map/MapProcessor
    at xaero.common.mods.SupportXaeroWorldmap.drawMinimap(SupportXaeroWorldmap.java:40)
    at xaero.common.minimap.render.MinimapFBORenderer.renderChunksToFBO(MinimapFBORenderer.java:129)
    at xaero.common.minimap.render.MinimapFBORenderer.renderChunks(MinimapFBORenderer.java:67)
    at xaero.common.minimap.render.MinimapRenderer.renderMinimap(MinimapRenderer.java:95)
    at xaero.common.minimap.MinimapProcessor.onRender(MinimapProcessor.java:149)
    at xaero.common.minimap.MinimapInterface.drawInterface(MinimapInterface.java:37)
    at xaero.common.interfaces.render.InterfaceRenderer.renderInterfaces(InterfaceRenderer.java:44)
    at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPreOverridable(ForgeEventHandler.java:108)
    at xaero.common.events.ForgeEventHandler.handleRenderGameOverlayEventPre(ForgeEventHandler.java:118)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2767_ForgeEventHandler_handleRenderGameOverlayEventPre_Pre.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:119)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: xaero.map.MapProcessor
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 24 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['RampagedAlpaca'/7515, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Chunk stats: MultiplayerChunkCache: 0, 0
  Level seed: 0
  Level generator: ID 11 - voidworld, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 2 game time, 2 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 2 total; [EntityPlayerSP['RampagedAlpaca'/7515, l='MpServer', x=8.50, y=65.00, z=8.50], EntityLatchedRenderer['unknown'/200, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Retry entities: 1 total; [EntityLatchedRenderer['unknown'/200, l='MpServer', x=8.50, y=65.00, z=8.50]]
  Server brand: ~~NULL~~
  Server type: Non-integrated multiplayer server

**Comment by Sunekaer** [comment]
https://www.feed-the-beast.com/projects/ftb-presents-stoneblock-2/files/2792347
